BASE_TASK_CONFIG_PATH: "configs/eval_pointnav_real_locobot.yaml"
TRAINER_NAME: "ppo"
ENV_NAME: "ROSNavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "out/eval_real_locobot/tb"
VIDEO_DIR: "out/eval_real_locobot/video_dir"
LOG_FILE: "out/eval_real_locobot/eval.log"
TEST_EPISODE_COUNT: 10
EVAL_CKPT_PATH_DIR: "out/ppo/checkpoints/pretrained_gibson.pth"
NUM_ENVIRONMENTS: 1
SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "out/ppo/checkpoints"
NUM_UPDATES: 270000
LOG_INTERVAL: 1
NUM_CHECKPOINTS: 1

EVAL:
    USE_CKPT_CONFIG: false
    DETERMINISTIC: true

RL:
  PPO:
    clip_param: 0.1
    ppo_epoch: 4
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.5
    num_steps: 128
    hidden_size: 512
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: True
    use_linear_lr_decay: True
    reward_window_size: 50

