ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  HABITAT_SIM_V0:
    ALLOW_SLIDING: false
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 69
    POSITION: [-0.015, 0.589, 0.047]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 90
    MIN_DEPTH: 0.155
    MAX_DEPTH: 10.0
    NORMALIZE: true
    POSITION: [0.000, 0.589, 0.047]
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
    HEIGHT: 0.65
    RADIUS: 0.18
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: PointNav-v1
  SPLIT: train
  DATA_PATH: "data/datasets/pointnav/gibson/v1/{split}/{split}.json.gz"

