SIMULATOR:
  HABITAT_SIM_V0:
    ALLOW_SLIDING: false
  RGB_SENSOR:
    WIDTH: 320                              # Scaled down (0.5)
    HEIGHT: 240                             # Scaled down (0.5)
    HFOV: 56                                # Measured on robot, docs give 69° (full res, not 4/3)
    POSITION: [-0.015, 0.589, 0.047]        # Measured on robot
  DEPTH_SENSOR:
    WIDTH: 320                              # Scaled down (0.5)
    HEIGHT: 240                             # Scaled down (0.5)
    HFOV: 80                                # Measured on robot, docs give 80°
    MIN_DEPTH: 0.155                        # Measured on robot, docs give 0.12m
    MAX_DEPTH: 10.0                         # From docs
    NORMALIZE: true
    POSITION: [0.000, 0.589, 0.047]         # Measured on robot
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
    HEIGHT: 0.65
    RADIUS: 0.18
  ACTION_SPACE_CONFIG: "pyrobotnoisy"
