ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  SCENE: "data/scene_datasets/citi/4d6ab9cc04f24c87aed802698f957b7a.glb"
  HABITAT_SIM_V0:
    ALLOW_SLIDING: false
  RGB_SENSOR:
    WIDTH: 160
    HEIGHT: 120
    HFOV: 56
    POSITION: [-0.015, 0.589, 0.047]
    ORIENTATION: [-0.349, 0, 0]
  DEPTH_SENSOR:
    WIDTH: 160
    HEIGHT: 120
    HFOV: 56 #80
    MIN_DEPTH: 0.155
    MAX_DEPTH: 10.0
    NORMALIZE_DEPTH: true
    POSITION: [-0.015, 0.589, 0.047] # [0.0, 0.589, 0.047]
    ORIENTATION: [-0.349, 0, 0]
  AGENT_0:
    SENSORS: ["RGB_SENSOR", "DEPTH_SENSOR"]
    HEIGHT: 0.65
    RADIUS: 0.22
  ACTION_SPACE_CONFIG: "v1"
  TURN_ANGLE: 30
DATASET:
  DATA_PATH: "data/datasets/pointnav/citi/v2/{split}/{split}.json.gz"
  SCENES_DIR: "data/scene_datasets/"
  SPLIT: "train"
  TYPE: "PointNav-v1"
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2
  SENSORS: ["POINTGOAL_WITH_GPS_COMPASS_SENSOR"]
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: "pointgoal_with_gps_compass"
  MEASUREMENTS: ["DISTANCE_TO_GOAL", "SUCCESS", "SPL", "SOFT_SPL"]
  SUCCESS:
    SUCCESS_DISTANCE: 0.2
