BASE_TASK_CONFIG_PATH: "configs/locobot_pointnav_citi_sim_simple.yaml"
TRAINER_NAME: "ddppo"
ENV_NAME: "NavRLEnv"
SIMULATOR_GPU_ID: 0
TORCH_GPU_ID: 0
VIDEO_OPTION: []
TENSORBOARD_DIR: "tb"
VIDEO_DIR: "video_dir"
TEST_EPISODE_COUNT: -1
EVAL_CKPT_PATH_DIR: "data/checkpoints"
NUM_PROCESSES: 1
SENSORS: ["DEPTH_SENSOR"]
CHECKPOINT_FOLDER: "data/checkpoints"
NUM_UPDATES: 10000
LOG_INTERVAL: 10
CHECKPOINT_INTERVAL: 250
RL:
  SUCCESS_REWARD: 2.5
  POLICY:
    name: "PointNavResNetPolicy"
  PPO:
    clip_param: 0.2
    ppo_epoch: 2
    num_mini_batch: 1
    value_loss_coef: 0.5
    entropy_coef: 0.01
    lr: 2.5e-4
    eps: 1e-5
    max_grad_norm: 0.2
    num_steps: 128
    use_gae: True
    gamma: 0.99
    tau: 0.95
    use_linear_clip_decay: False
    use_linear_lr_decay: False
    reward_window_size: 50
    use_normalized_advantage: False
    hidden_size: 512
  DDPPO:
    sync_frac: 0.6
    distrib_backend: GLOO
    pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
    pretrained: False
    pretrained_encoder: False
    train_encoder: True
    reset_critic: True
    backbone: resnet50
    rnn_type: LSTM
    num_recurrent_layers: 2
